import type { NextPage } from 'next'
import Head from 'next/head'
import ChatPage from '../components/ChatPage'
import AuthProvider from '../contexts/auth_context'

const Home: NextPage = () => {
	return (
		<div >
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<AuthProvider>
				<ChatPage />
			</AuthProvider>

		</div>

	)
}

export default Home
